AllCops:
  Newcops: enable
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'features/**/*'
Metrics/AbcSize:
  Max: 20