version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-rails
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - RAILS_ENV=production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/VehicleMinders
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - web
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-rails
    environment:
      - AWS_ACCESS_KEY_ID=AKIAYNGZZEYJPEMVO63K
      - AWS_SECRET_ACCESS_KEY=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
      - RAILS_ENV=production
    command: bundle exec sidekiq
    volumes:
      - .:/VehicleMinders